version: '3.8'

services:
  nl2sql-app:
    build:
      context: .
    container_name: nl2sql-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./vectorstore:/app/vectorstore
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLE_CORS: "false"
      STREAMLIT_SERVER_PORT: "8080"
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
    restart: unless-stopped
