services:
  - type: web
    name: askyourdb
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        fromDotEnv: true
    healthCheckPath: /
    ports:
      - 8080